// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BlockSignatures string
	Blocks          string
	Delegations     string
	Posts           string
	Transactions    string
	Validators      string
}{
	BlockSignatures: "block_signatures",
	Blocks:          "blocks",
	Delegations:     "delegations",
	Posts:           "posts",
	Transactions:    "transactions",
	Validators:      "validators",
}
