// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BlockSignatures string
	Blocks          string
	Posts           string
	Stakes          string
	SyncLogs        string
	Transactions    string
	Upvotes         string
	Validators      string
}{
	BlockSignatures: "block_signatures",
	Blocks:          "blocks",
	Posts:           "posts",
	Stakes:          "stakes",
	SyncLogs:        "sync_logs",
	Transactions:    "transactions",
	Upvotes:         "upvotes",
	Validators:      "validators",
}
