// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BlockSignatures string
	Blocks          string
	Posts           string
	SlashingEvents  string
	SocialGraph     string
	Stakes          string
	SyncLogs        string
	Transactions    string
	UpvoteRewards   string
	Upvotes         string
	Validators      string
}{
	BlockSignatures: "block_signatures",
	Blocks:          "blocks",
	Posts:           "posts",
	SlashingEvents:  "slashing_events",
	SocialGraph:     "social_graph",
	Stakes:          "stakes",
	SyncLogs:        "sync_logs",
	Transactions:    "transactions",
	UpvoteRewards:   "upvote_rewards",
	Upvotes:         "upvotes",
	Validators:      "validators",
}
