// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPreCommits(t *testing.T) {
	t.Parallel()

	query := PreCommits()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPreCommitsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPreCommitsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PreCommits().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPreCommitsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PreCommitSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPreCommitsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PreCommitExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PreCommit exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PreCommitExists to return true, but got false.")
	}
}

func testPreCommitsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	preCommitFound, err := FindPreCommit(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if preCommitFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPreCommitsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PreCommits().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPreCommitsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PreCommits().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPreCommitsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	preCommitOne := &PreCommit{}
	preCommitTwo := &PreCommit{}
	if err = randomize.Struct(seed, preCommitOne, preCommitDBTypes, false, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}
	if err = randomize.Struct(seed, preCommitTwo, preCommitDBTypes, false, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = preCommitOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = preCommitTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PreCommits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPreCommitsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	preCommitOne := &PreCommit{}
	preCommitTwo := &PreCommit{}
	if err = randomize.Struct(seed, preCommitOne, preCommitDBTypes, false, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}
	if err = randomize.Struct(seed, preCommitTwo, preCommitDBTypes, false, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = preCommitOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = preCommitTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func preCommitBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func preCommitAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PreCommit) error {
	*o = PreCommit{}
	return nil
}

func testPreCommitsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &PreCommit{}
	o := &PreCommit{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, preCommitDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PreCommit object: %s", err)
	}

	AddPreCommitHook(boil.BeforeInsertHook, preCommitBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	preCommitBeforeInsertHooks = []PreCommitHook{}

	AddPreCommitHook(boil.AfterInsertHook, preCommitAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	preCommitAfterInsertHooks = []PreCommitHook{}

	AddPreCommitHook(boil.AfterSelectHook, preCommitAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	preCommitAfterSelectHooks = []PreCommitHook{}

	AddPreCommitHook(boil.BeforeUpdateHook, preCommitBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	preCommitBeforeUpdateHooks = []PreCommitHook{}

	AddPreCommitHook(boil.AfterUpdateHook, preCommitAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	preCommitAfterUpdateHooks = []PreCommitHook{}

	AddPreCommitHook(boil.BeforeDeleteHook, preCommitBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	preCommitBeforeDeleteHooks = []PreCommitHook{}

	AddPreCommitHook(boil.AfterDeleteHook, preCommitAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	preCommitAfterDeleteHooks = []PreCommitHook{}

	AddPreCommitHook(boil.BeforeUpsertHook, preCommitBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	preCommitBeforeUpsertHooks = []PreCommitHook{}

	AddPreCommitHook(boil.AfterUpsertHook, preCommitAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	preCommitAfterUpsertHooks = []PreCommitHook{}
}

func testPreCommitsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPreCommitsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(preCommitColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPreCommitToOneValidatorUsingValidator(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local PreCommit
	var foreign Validator

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, preCommitDBTypes, false, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, validatorDBTypes, false, validatorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Validator struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ValidatorAddress = foreign.Address
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Validator().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.Address != foreign.Address {
		t.Errorf("want: %v, got %v", foreign.Address, check.Address)
	}

	slice := PreCommitSlice{&local}
	if err = local.L.LoadValidator(ctx, tx, false, (*[]*PreCommit)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Validator == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Validator = nil
	if err = local.L.LoadValidator(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Validator == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPreCommitToOneSetOpValidatorUsingValidator(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PreCommit
	var b, c Validator

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, preCommitDBTypes, false, strmangle.SetComplement(preCommitPrimaryKeyColumns, preCommitColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, validatorDBTypes, false, strmangle.SetComplement(validatorPrimaryKeyColumns, validatorColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, validatorDBTypes, false, strmangle.SetComplement(validatorPrimaryKeyColumns, validatorColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Validator{&b, &c} {
		err = a.SetValidator(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Validator != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ValidatorAddressPreCommits[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ValidatorAddress != x.Address {
			t.Error("foreign key was wrong value", a.ValidatorAddress)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ValidatorAddress))
		reflect.Indirect(reflect.ValueOf(&a.ValidatorAddress)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ValidatorAddress != x.Address {
			t.Error("foreign key was wrong value", a.ValidatorAddress, x.Address)
		}
	}
}

func testPreCommitsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPreCommitsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PreCommitSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPreCommitsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PreCommits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	preCommitDBTypes = map[string]string{`ID`: `integer`, `Height`: `integer`, `Round`: `integer`, `ValidatorAddress`: `text`, `PreCommitTimestamp`: `timestamp without time zone`, `VotingPower`: `integer`, `ProposerPriority`: `integer`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `DeletedAt`: `timestamp without time zone`}
	_                = bytes.MinRead
)

func testPreCommitsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(preCommitPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(preCommitAllColumns) == len(preCommitPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPreCommitsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(preCommitAllColumns) == len(preCommitPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PreCommit{}
	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, preCommitDBTypes, true, preCommitPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(preCommitAllColumns, preCommitPrimaryKeyColumns) {
		fields = preCommitAllColumns
	} else {
		fields = strmangle.SetComplement(
			preCommitAllColumns,
			preCommitPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PreCommitSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPreCommitsUpsert(t *testing.T) {
	t.Parallel()

	if len(preCommitAllColumns) == len(preCommitPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PreCommit{}
	if err = randomize.Struct(seed, &o, preCommitDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PreCommit: %s", err)
	}

	count, err := PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, preCommitDBTypes, false, preCommitPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PreCommit struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PreCommit: %s", err)
	}

	count, err = PreCommits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
