// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BlockSignatures", testBlockSignaturesUpsert)

	t.Run("Blocks", testBlocksUpsert)

	t.Run("Delegations", testDelegationsUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("Transactions", testTransactionsUpsert)

	t.Run("Validators", testValidatorsUpsert)
}
