// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SocialGraph is an object representing the database table.
type SocialGraph struct {
	ID               int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Amount           int64     `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	BuyerAddress     string    `boil:"buyer_address" json:"buyerAddress" toml:"buyerAddress" yaml:"buyerAddress"`
	CreatorAddress   string    `boil:"creator_address" json:"creatorAddress" toml:"creatorAddress" yaml:"creatorAddress"`
	Username         string    `boil:"username" json:"username" toml:"username" yaml:"username"`
	ValidatorAddress string    `boil:"validator_address" json:"validatorAddress" toml:"validatorAddress" yaml:"validatorAddress"`
	CreatedAt        time.Time `boil:"created_at" json:"createdAt" toml:"createdAt" yaml:"createdAt"`
	UpdatedAt        time.Time `boil:"updated_at" json:"updatedAt" toml:"updatedAt" yaml:"updatedAt"`
	DeletedAt        null.Time `boil:"deleted_at" json:"deletedAt,omitempty" toml:"deletedAt" yaml:"deletedAt,omitempty"`

	R *socialGraphR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L socialGraphL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SocialGraphColumns = struct {
	ID               string
	Amount           string
	BuyerAddress     string
	CreatorAddress   string
	Username         string
	ValidatorAddress string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        string
}{
	ID:               "id",
	Amount:           "amount",
	BuyerAddress:     "buyer_address",
	CreatorAddress:   "creator_address",
	Username:         "username",
	ValidatorAddress: "validator_address",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
}

// Generated where

var SocialGraphWhere = struct {
	ID               whereHelperint64
	Amount           whereHelperint64
	BuyerAddress     whereHelperstring
	CreatorAddress   whereHelperstring
	Username         whereHelperstring
	ValidatorAddress whereHelperstring
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpertime_Time
	DeletedAt        whereHelpernull_Time
}{
	ID:               whereHelperint64{field: "\"social_graph\".\"id\""},
	Amount:           whereHelperint64{field: "\"social_graph\".\"amount\""},
	BuyerAddress:     whereHelperstring{field: "\"social_graph\".\"buyer_address\""},
	CreatorAddress:   whereHelperstring{field: "\"social_graph\".\"creator_address\""},
	Username:         whereHelperstring{field: "\"social_graph\".\"username\""},
	ValidatorAddress: whereHelperstring{field: "\"social_graph\".\"validator_address\""},
	CreatedAt:        whereHelpertime_Time{field: "\"social_graph\".\"created_at\""},
	UpdatedAt:        whereHelpertime_Time{field: "\"social_graph\".\"updated_at\""},
	DeletedAt:        whereHelpernull_Time{field: "\"social_graph\".\"deleted_at\""},
}

// SocialGraphRels is where relationship names are stored.
var SocialGraphRels = struct {
}{}

// socialGraphR is where relationships are stored.
type socialGraphR struct {
}

// NewStruct creates a new relationship struct
func (*socialGraphR) NewStruct() *socialGraphR {
	return &socialGraphR{}
}

// socialGraphL is where Load methods for each relationship are stored.
type socialGraphL struct{}

var (
	socialGraphAllColumns            = []string{"id", "amount", "buyer_address", "creator_address", "username", "validator_address", "created_at", "updated_at", "deleted_at"}
	socialGraphColumnsWithoutDefault = []string{"amount", "buyer_address", "creator_address", "username", "validator_address", "deleted_at"}
	socialGraphColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	socialGraphPrimaryKeyColumns     = []string{"id"}
)

type (
	// SocialGraphSlice is an alias for a slice of pointers to SocialGraph.
	// This should generally be used opposed to []SocialGraph.
	SocialGraphSlice []*SocialGraph

	socialGraphQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	socialGraphType                 = reflect.TypeOf(&SocialGraph{})
	socialGraphMapping              = queries.MakeStructMapping(socialGraphType)
	socialGraphPrimaryKeyMapping, _ = queries.BindMapping(socialGraphType, socialGraphMapping, socialGraphPrimaryKeyColumns)
	socialGraphInsertCacheMut       sync.RWMutex
	socialGraphInsertCache          = make(map[string]insertCache)
	socialGraphUpdateCacheMut       sync.RWMutex
	socialGraphUpdateCache          = make(map[string]updateCache)
	socialGraphUpsertCacheMut       sync.RWMutex
	socialGraphUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single socialGraph record from the query.
func (q socialGraphQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SocialGraph, error) {
	o := &SocialGraph{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for social_graph")
	}

	return o, nil
}

// All returns all SocialGraph records from the query.
func (q socialGraphQuery) All(ctx context.Context, exec boil.ContextExecutor) (SocialGraphSlice, error) {
	var o []*SocialGraph

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SocialGraph slice")
	}

	return o, nil
}

// Count returns the count of all SocialGraph records in the query.
func (q socialGraphQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count social_graph rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q socialGraphQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if social_graph exists")
	}

	return count > 0, nil
}

// SocialGraphs retrieves all the records using an executor.
func SocialGraphs(mods ...qm.QueryMod) socialGraphQuery {
	mods = append(mods, qm.From("\"social_graph\""))
	return socialGraphQuery{NewQuery(mods...)}
}

// FindSocialGraph retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSocialGraph(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*SocialGraph, error) {
	socialGraphObj := &SocialGraph{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"social_graph\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, socialGraphObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from social_graph")
	}

	return socialGraphObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SocialGraph) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no social_graph provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(socialGraphColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	socialGraphInsertCacheMut.RLock()
	cache, cached := socialGraphInsertCache[key]
	socialGraphInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			socialGraphAllColumns,
			socialGraphColumnsWithDefault,
			socialGraphColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(socialGraphType, socialGraphMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(socialGraphType, socialGraphMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"social_graph\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"social_graph\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into social_graph")
	}

	if !cached {
		socialGraphInsertCacheMut.Lock()
		socialGraphInsertCache[key] = cache
		socialGraphInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the SocialGraph.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SocialGraph) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	socialGraphUpdateCacheMut.RLock()
	cache, cached := socialGraphUpdateCache[key]
	socialGraphUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			socialGraphAllColumns,
			socialGraphPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update social_graph, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"social_graph\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, socialGraphPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(socialGraphType, socialGraphMapping, append(wl, socialGraphPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update social_graph row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for social_graph")
	}

	if !cached {
		socialGraphUpdateCacheMut.Lock()
		socialGraphUpdateCache[key] = cache
		socialGraphUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q socialGraphQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for social_graph")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for social_graph")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SocialGraphSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), socialGraphPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"social_graph\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, socialGraphPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in socialGraph slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all socialGraph")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SocialGraph) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no social_graph provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(socialGraphColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	socialGraphUpsertCacheMut.RLock()
	cache, cached := socialGraphUpsertCache[key]
	socialGraphUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			socialGraphAllColumns,
			socialGraphColumnsWithDefault,
			socialGraphColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			socialGraphAllColumns,
			socialGraphPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert social_graph, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(socialGraphPrimaryKeyColumns))
			copy(conflict, socialGraphPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"social_graph\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(socialGraphType, socialGraphMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(socialGraphType, socialGraphMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert social_graph")
	}

	if !cached {
		socialGraphUpsertCacheMut.Lock()
		socialGraphUpsertCache[key] = cache
		socialGraphUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single SocialGraph record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SocialGraph) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SocialGraph provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), socialGraphPrimaryKeyMapping)
	sql := "DELETE FROM \"social_graph\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from social_graph")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for social_graph")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q socialGraphQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no socialGraphQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from social_graph")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for social_graph")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SocialGraphSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), socialGraphPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"social_graph\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, socialGraphPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from socialGraph slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for social_graph")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SocialGraph) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSocialGraph(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SocialGraphSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SocialGraphSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), socialGraphPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"social_graph\".* FROM \"social_graph\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, socialGraphPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SocialGraphSlice")
	}

	*o = slice

	return nil
}

// SocialGraphExists checks if the SocialGraph row exists.
func SocialGraphExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"social_graph\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if social_graph exists")
	}

	return exists, nil
}
