// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UpvoteReward is an object representing the database table.
type UpvoteReward struct {
	ID            int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Height        int64     `boil:"height" json:"height" toml:"height" yaml:"height"`
	VendorID      int       `boil:"vendor_id" json:"vendorID" toml:"vendorID" yaml:"vendorID"`
	PostID        string    `boil:"post_id" json:"postID" toml:"postID" yaml:"postID"`
	RewardAddress string    `boil:"reward_address" json:"rewardAddress" toml:"rewardAddress" yaml:"rewardAddress"`
	RewardAmount  int64     `boil:"reward_amount" json:"rewardAmount" toml:"rewardAmount" yaml:"rewardAmount"`
	CreatedAt     time.Time `boil:"created_at" json:"createdAt" toml:"createdAt" yaml:"createdAt"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updatedAt" toml:"updatedAt" yaml:"updatedAt"`
	DeletedAt     null.Time `boil:"deleted_at" json:"deletedAt,omitempty" toml:"deletedAt" yaml:"deletedAt,omitempty"`

	R *upvoteRewardR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L upvoteRewardL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UpvoteRewardColumns = struct {
	ID            string
	Height        string
	VendorID      string
	PostID        string
	RewardAddress string
	RewardAmount  string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     string
}{
	ID:            "id",
	Height:        "height",
	VendorID:      "vendor_id",
	PostID:        "post_id",
	RewardAddress: "reward_address",
	RewardAmount:  "reward_amount",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	DeletedAt:     "deleted_at",
}

// Generated where

var UpvoteRewardWhere = struct {
	ID            whereHelperint
	Height        whereHelperint64
	VendorID      whereHelperint
	PostID        whereHelperstring
	RewardAddress whereHelperstring
	RewardAmount  whereHelperint64
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
	DeletedAt     whereHelpernull_Time
}{
	ID:            whereHelperint{field: "\"upvote_rewards\".\"id\""},
	Height:        whereHelperint64{field: "\"upvote_rewards\".\"height\""},
	VendorID:      whereHelperint{field: "\"upvote_rewards\".\"vendor_id\""},
	PostID:        whereHelperstring{field: "\"upvote_rewards\".\"post_id\""},
	RewardAddress: whereHelperstring{field: "\"upvote_rewards\".\"reward_address\""},
	RewardAmount:  whereHelperint64{field: "\"upvote_rewards\".\"reward_amount\""},
	CreatedAt:     whereHelpertime_Time{field: "\"upvote_rewards\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"upvote_rewards\".\"updated_at\""},
	DeletedAt:     whereHelpernull_Time{field: "\"upvote_rewards\".\"deleted_at\""},
}

// UpvoteRewardRels is where relationship names are stored.
var UpvoteRewardRels = struct {
}{}

// upvoteRewardR is where relationships are stored.
type upvoteRewardR struct {
}

// NewStruct creates a new relationship struct
func (*upvoteRewardR) NewStruct() *upvoteRewardR {
	return &upvoteRewardR{}
}

// upvoteRewardL is where Load methods for each relationship are stored.
type upvoteRewardL struct{}

var (
	upvoteRewardAllColumns            = []string{"id", "height", "vendor_id", "post_id", "reward_address", "reward_amount", "created_at", "updated_at", "deleted_at"}
	upvoteRewardColumnsWithoutDefault = []string{"height", "vendor_id", "post_id", "reward_address", "reward_amount", "deleted_at"}
	upvoteRewardColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	upvoteRewardPrimaryKeyColumns     = []string{"id"}
)

type (
	// UpvoteRewardSlice is an alias for a slice of pointers to UpvoteReward.
	// This should generally be used opposed to []UpvoteReward.
	UpvoteRewardSlice []*UpvoteReward

	upvoteRewardQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	upvoteRewardType                 = reflect.TypeOf(&UpvoteReward{})
	upvoteRewardMapping              = queries.MakeStructMapping(upvoteRewardType)
	upvoteRewardPrimaryKeyMapping, _ = queries.BindMapping(upvoteRewardType, upvoteRewardMapping, upvoteRewardPrimaryKeyColumns)
	upvoteRewardInsertCacheMut       sync.RWMutex
	upvoteRewardInsertCache          = make(map[string]insertCache)
	upvoteRewardUpdateCacheMut       sync.RWMutex
	upvoteRewardUpdateCache          = make(map[string]updateCache)
	upvoteRewardUpsertCacheMut       sync.RWMutex
	upvoteRewardUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single upvoteReward record from the query.
func (q upvoteRewardQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UpvoteReward, error) {
	o := &UpvoteReward{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for upvote_rewards")
	}

	return o, nil
}

// All returns all UpvoteReward records from the query.
func (q upvoteRewardQuery) All(ctx context.Context, exec boil.ContextExecutor) (UpvoteRewardSlice, error) {
	var o []*UpvoteReward

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UpvoteReward slice")
	}

	return o, nil
}

// Count returns the count of all UpvoteReward records in the query.
func (q upvoteRewardQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count upvote_rewards rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q upvoteRewardQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if upvote_rewards exists")
	}

	return count > 0, nil
}

// UpvoteRewards retrieves all the records using an executor.
func UpvoteRewards(mods ...qm.QueryMod) upvoteRewardQuery {
	mods = append(mods, qm.From("\"upvote_rewards\""))
	return upvoteRewardQuery{NewQuery(mods...)}
}

// FindUpvoteReward retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUpvoteReward(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*UpvoteReward, error) {
	upvoteRewardObj := &UpvoteReward{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"upvote_rewards\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, upvoteRewardObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from upvote_rewards")
	}

	return upvoteRewardObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UpvoteReward) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no upvote_rewards provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(upvoteRewardColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	upvoteRewardInsertCacheMut.RLock()
	cache, cached := upvoteRewardInsertCache[key]
	upvoteRewardInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			upvoteRewardAllColumns,
			upvoteRewardColumnsWithDefault,
			upvoteRewardColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(upvoteRewardType, upvoteRewardMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(upvoteRewardType, upvoteRewardMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"upvote_rewards\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"upvote_rewards\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into upvote_rewards")
	}

	if !cached {
		upvoteRewardInsertCacheMut.Lock()
		upvoteRewardInsertCache[key] = cache
		upvoteRewardInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the UpvoteReward.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UpvoteReward) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	upvoteRewardUpdateCacheMut.RLock()
	cache, cached := upvoteRewardUpdateCache[key]
	upvoteRewardUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			upvoteRewardAllColumns,
			upvoteRewardPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update upvote_rewards, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"upvote_rewards\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, upvoteRewardPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(upvoteRewardType, upvoteRewardMapping, append(wl, upvoteRewardPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update upvote_rewards row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for upvote_rewards")
	}

	if !cached {
		upvoteRewardUpdateCacheMut.Lock()
		upvoteRewardUpdateCache[key] = cache
		upvoteRewardUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q upvoteRewardQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for upvote_rewards")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for upvote_rewards")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UpvoteRewardSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upvoteRewardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"upvote_rewards\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, upvoteRewardPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in upvoteReward slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all upvoteReward")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UpvoteReward) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no upvote_rewards provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(upvoteRewardColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	upvoteRewardUpsertCacheMut.RLock()
	cache, cached := upvoteRewardUpsertCache[key]
	upvoteRewardUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			upvoteRewardAllColumns,
			upvoteRewardColumnsWithDefault,
			upvoteRewardColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			upvoteRewardAllColumns,
			upvoteRewardPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert upvote_rewards, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(upvoteRewardPrimaryKeyColumns))
			copy(conflict, upvoteRewardPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"upvote_rewards\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(upvoteRewardType, upvoteRewardMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(upvoteRewardType, upvoteRewardMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert upvote_rewards")
	}

	if !cached {
		upvoteRewardUpsertCacheMut.Lock()
		upvoteRewardUpsertCache[key] = cache
		upvoteRewardUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single UpvoteReward record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UpvoteReward) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UpvoteReward provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), upvoteRewardPrimaryKeyMapping)
	sql := "DELETE FROM \"upvote_rewards\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from upvote_rewards")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for upvote_rewards")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q upvoteRewardQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no upvoteRewardQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from upvote_rewards")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for upvote_rewards")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UpvoteRewardSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upvoteRewardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"upvote_rewards\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, upvoteRewardPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from upvoteReward slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for upvote_rewards")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UpvoteReward) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUpvoteReward(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UpvoteRewardSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UpvoteRewardSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upvoteRewardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"upvote_rewards\".* FROM \"upvote_rewards\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, upvoteRewardPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UpvoteRewardSlice")
	}

	*o = slice

	return nil
}

// UpvoteRewardExists checks if the UpvoteReward row exists.
func UpvoteRewardExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"upvote_rewards\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if upvote_rewards exists")
	}

	return exists, nil
}
